import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { InvoiceItem } from '../types';

export function exportSingleInvoicePdf(invoice: InvoiceItem) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Brand Colors
  const royalBlue = [37, 99, 235];
  const darkSlate = [30, 41, 59];

  // Header Banner
  doc.setFillColor(royalBlue[0], royalBlue[1], royalBlue[2]);
  doc.rect(0, 0, 210, 28, 'F');

  // Title in Header
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('ROYAL TAILOR SHOP', 14, 12);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Simplified Tax Invoice - ZATCA Compliant', 14, 19);
  doc.text('VAT ID: 310294857300003 | CR: 1010892415', 14, 24);

  // Shop Details on Right
  doc.setFontSize(9);
  doc.text('King Fahd Road, Riyadh, KSA', 196, 12, { align: 'right' });
  doc.text('Tel: +966 11 456 7890', 196, 17, { align: 'right' });
  doc.text('manager@royaltailor.sa', 196, 22, { align: 'right' });

  // Invoice Metadata Box
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE INFORMATION / BIKAYA DETAILS', 14, 38);

  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 42, 182, 30, 3, 3, 'FD');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Invoice Number:', 18, 49);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.invoiceNumber, 48, 49);

  doc.setFont('helvetica', 'bold');
  doc.text('Date & Time:', 18, 56);
  doc.setFont('helvetica', 'normal');
  doc.text(`${invoice.dateLabel} - ${invoice.timeLabel}`, 48, 56);

  doc.setFont('helvetica', 'bold');
  doc.text('Customer Name:', 18, 63);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.customerName, 48, 63);

  doc.setFont('helvetica', 'bold');
  doc.text('Payment Method:', 115, 49);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.paymentMethod, 150, 49);

  doc.setFont('helvetica', 'bold');
  doc.text('Payment Status:', 115, 56);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.status === 'paid' ? 'PAID IN FULL' : 'PARTIAL PAYMENT', 150, 56);

  doc.setFont('helvetica', 'bold');
  doc.text('Customer Phone:', 115, 63);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.customerPhone || 'N/A', 150, 63);

  // Items Table
  const subtotal = (invoice.amount - invoice.vatAmount).toFixed(2);
  const vatAmount = invoice.vatAmount.toFixed(2);
  const totalAmount = invoice.amount.toFixed(2);

  autoTable(doc, {
    startY: 78,
    head: [['#', 'Item / Garment Description', 'Qty', 'Unit Price (SAR)', 'VAT (15%)', 'Total (SAR)']],
    body: [
      ['1', invoice.description, '1', subtotal, vatAmount, totalAmount],
    ],
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'center',
    },
    bodyStyles: {
      fontSize: 9,
      halign: 'center',
    },
    columnStyles: {
      1: { halign: 'left' },
    },
    theme: 'striped',
  });

  const finalY = (doc as any).lastAutoTable.finalY + 8;

  // Summary Table on Right
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(120, finalY, 76, 36, 3, 3, 'FD');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Subtotal (Excl. VAT):', 124, finalY + 8);
  doc.text(`${subtotal} SAR`, 190, finalY + 8, { align: 'right' });

  doc.text('VAT Amount (15%):', 124, finalY + 16);
  doc.text(`${vatAmount} SAR`, 190, finalY + 16, { align: 'right' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Grand Total (Incl. VAT):', 124, finalY + 25);
  doc.setTextColor(37, 99, 235);
  doc.text(`${totalAmount} SAR`, 190, finalY + 25, { align: 'right' });

  if (invoice.remainingAmount > 0) {
    doc.setTextColor(225, 29, 72);
    doc.text('Remaining Balance:', 124, finalY + 32);
    doc.text(`${invoice.remainingAmount} SAR`, 190, finalY + 32, { align: 'right' });
  }

  // Stamp & ZATCA Verification Box
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.roundedRect(14, finalY, 95, 36, 3, 3, 'FD');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('ZATCA E-INVOICE VERIFICATION CODE', 18, finalY + 7);
  doc.setFont('helvetica', 'normal');
  doc.text('Cryptographic Stamp: 7f8a9b2c3d4e5f60718293a4b5c6d7e8', 18, finalY + 13);
  doc.text('Status: Compliant with Saudi E-Invoicing Phase 2', 18, finalY + 18);
  doc.text('Generated by Royal Tailor Shop ERP System v3.4', 18, finalY + 23);
  doc.text('Signature / Stamp: Verified & Authenticated', 18, finalY + 28);

  // Footer Note
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Thank you for choosing Royal Tailor Shop. Goods tailored to custom measurements cannot be returned.', 105, 285, { align: 'center' });

  // Save the PDF file
  doc.save(`Invoice_${invoice.invoiceNumber.replace('#', '')}.pdf`);
}

export function exportFinancialQuarterReportPdf(invoices: InvoiceItem[]) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const royalBlue = [37, 99, 235];
  const darkSlate = [30, 41, 59];

  // Header Banner
  doc.setFillColor(royalBlue[0], royalBlue[1], royalBlue[2]);
  doc.rect(0, 0, 210, 32, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('ROYAL TAILOR SHOP - FINANCIAL REPORT', 14, 13);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Q2 Comprehensive Accounting Ledger & Tax Declaration', 14, 21);
  doc.text(`Report Generated: ${new Date().toLocaleDateString()} | Branch: Main Riyadh Branch`, 14, 27);

  // KPI Overview Cards (3 Cards)
  const totalRevenues = invoices.reduce((acc, i) => acc + i.amount, 0);
  const totalVat = invoices.reduce((acc, i) => acc + i.vatAmount, 0);
  const totalCollected = invoices.reduce((acc, i) => acc + i.paidAmount, 0);

  // Card 1
  doc.setFillColor(241, 245, 249);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 38, 56, 22, 2, 2, 'FD');
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.text('TOTAL REVENUE', 18, 44);
  doc.setTextColor(37, 99, 235);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`${totalRevenues.toLocaleString()} SAR`, 18, 53);

  // Card 2
  doc.roundedRect(77, 38, 56, 22, 2, 2, 'FD');
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('TOTAL VAT (15%)', 81, 44);
  doc.setTextColor(16, 185, 129);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`${totalVat.toFixed(2)} SAR`, 81, 53);

  // Card 3
  doc.roundedRect(140, 38, 56, 22, 2, 2, 'FD');
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('COLLECTED FUNDS', 144, 44);
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`${totalCollected.toLocaleString()} SAR`, 144, 53);

  // Section Header: Detailed Invoices Table
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE LEDGER REGISTER (ALL ISSUED TRANSACTIONS)', 14, 68);

  const tableRows = invoices.map((i, idx) => [
    (idx + 1).toString(),
    i.invoiceNumber,
    i.customerName,
    i.dateLabel,
    i.paymentMethod,
    `${i.vatAmount.toFixed(2)}`,
    `${i.amount.toFixed(2)}`,
    i.status.toUpperCase(),
  ]);

  autoTable(doc, {
    startY: 72,
    head: [['#', 'Invoice #', 'Customer Name', 'Date', 'Method', 'VAT (15%)', 'Total (SAR)', 'Status']],
    body: tableRows,
    headStyles: {
      fillColor: [37, 99, 235],
      textColor: [255, 255, 255],
      fontSize: 8,
      halign: 'center',
    },
    bodyStyles: {
      fontSize: 8,
      halign: 'center',
    },
    columnStyles: {
      2: { halign: 'left' },
    },
    theme: 'grid',
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;

  // Accountant Certification Box
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, finalY, 182, 32, 2, 2, 'FD');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.text('ACCOUNTANT APPROVAL & AUDIT CERTIFICATION', 18, finalY + 8);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text('I hereby certify that this financial report accurately represents the invoices, collected sales, and tax receipts.', 18, finalY + 15);
  doc.text('Chief Accountant: Rafiq Ahmed / CPA Certified', 18, finalY + 21);
  doc.text('General Manager: Abdulrahman Al-Subaie | Royal Tailor Shop Management', 18, finalY + 26);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Page 1 of 1 | Royal Tailor Shop ERP | Confidential Financial Document', 105, 285, { align: 'center' });

  // Save PDF
  doc.save(`Financial_Report_Q2_${new Date().toISOString().split('T')[0]}.pdf`);
}
