import { FabricRoll, OrderItem, InvoiceItem, StaffMember, AuditLogItem, GarmentOption } from './types';

export const INITIAL_GARMENTS: GarmentOption[] = [
  {
    id: 'traditional_thobe',
    title: 'ثوب تقليدي / قطري / كويتي',
    badge: 'محدد',
    description: 'ياقة قلاب / سادة، أكمام كبك أو مفتوحة، خياطة مخفية',
    details: 'قصة كلاسيكية أنيقة تناسب جميع المناسبات الرسمية واليومية مع تقفيل يدوي عالي الدقة.',
    basePrice: 450,
  },
  {
    id: 'formal_shirt',
    title: 'قميص رسمي / كاجوال',
    description: 'ياقة إيطالية كلاسيكية، جيب أمامي، أزرار صدف طبيعي',
    details: 'تفصيل إيطالي فائق الراحة بأقمشة قطنية 100% مقاومة للتجعد.',
    basePrice: 280,
  },
  {
    id: 'luxury_blazer',
    title: 'جاكيت / بليزر رسمي',
    description: 'قصة سليم فت، بطانة حريرية إيطالية، أزرار نحاسية فخمة',
    details: 'بدلة رجالية فاخرة مبطنة بالحرير ومصنوعة من أجود أنواع الصوف الخالص.',
    basePrice: 1200,
  },
];

export const INITIAL_FABRICS: FabricRoll[] = [
  {
    id: 'fab-1',
    code: 'TY-88#',
    name: 'تويوبو ملكي ياباني أصلي',
    origin: 'اليابان',
    flag: 'JP',
    widthInches: 58,
    colorName: 'أبيض سكري',
    remainingMeters: 42.5,
    totalMeters: 50.0,
    costPrice: 35,
    retailPrice: 65,
    stockStatus: 'available',
  },
  {
    id: 'fab-2',
    code: 'RC-402#',
    name: 'ريتشي صيفي فاخر',
    origin: 'السعودية',
    flag: 'SA',
    widthInches: 58,
    colorName: 'كريمي فاتح',
    remainingMeters: 12.0,
    totalMeters: 50.0,
    costPrice: 42,
    retailPrice: 80,
    stockStatus: 'critical',
    alertMessage: 'المخزون قارب على النفاد! يتبقى ما يكفي لـ 3 أثواب فقط.',
  },
  {
    id: 'fab-3',
    code: 'ENG-12#',
    name: 'صوف إنجليزي هدرسفيلد',
    origin: 'بريطانيا',
    flag: 'UK',
    widthInches: 60,
    colorName: 'كحلي ملكي مقلم',
    remainingMeters: 28.0,
    totalMeters: 30.0,
    costPrice: 140,
    retailPrice: 260,
    stockStatus: 'good',
  },
  {
    id: 'fab-4',
    code: 'SW-99#',
    name: 'سويسري سبيشال كلاسيك',
    origin: 'سويسرا',
    flag: 'CH',
    widthInches: 58,
    colorName: 'ناصع البياض',
    remainingMeters: 34.0,
    totalMeters: 50.0,
    costPrice: 60,
    retailPrice: 110,
    stockStatus: 'medium',
  },
  {
    id: 'fab-5',
    code: 'KSL-441#',
    name: 'حرير كوري كحلي داكن',
    origin: 'كوريا',
    flag: 'KR',
    widthInches: 58,
    colorName: 'كحلي داكن',
    remainingMeters: 8.0,
    totalMeters: 30.0,
    costPrice: 55,
    retailPrice: 120,
    stockStatus: 'critical',
    alertMessage: 'وصل للحد الأدنى المسموح به للموسم الحالي.',
  },
  {
    id: 'fab-6',
    code: 'FL-108#',
    name: 'تويوبو بلاتينيوم ياباني',
    origin: 'اليابان',
    flag: 'JP',
    widthInches: 58,
    colorName: 'ربع واقف ناعم',
    remainingMeters: 45.0,
    totalMeters: 50.0,
    costPrice: 40,
    retailPrice: 75,
    stockStatus: 'available',
  },
];

export const INITIAL_ORDERS: OrderItem[] = [
  {
    id: 'ord-8942',
    orderNumber: 'ORD-8942#',
    customerName: 'محمد عبد الله الغامدي',
    customerPhone: '055 123 4567',
    isVip: true,
    status: 'tailoring',
    statusLabel: 'قيد التفصيل',
    priority: 'normal',
    deliveryDate: '2024-10-24',
    deliveryDateLabel: 'الخميس، 24 أكتوبر 2024',
    garmentType: 'traditional_thobe',
    garmentTitle: 'ثوب تقليدي / قطري / كويتي',
    garmentSubtitle: 'ياقة قلاب / سادة، أكمام كبك أو مفتوحة، خياطة مخفية',
    piecesCount: 1,
    progressPercent: 65,
    currentStageName: 'مرحلة البروفة وتثبيت الرقبة',
    tailorName: 'المعلم سراج',
    tailorVerified: true,
    measurements: {
      length: 152,
      shoulder: 46,
      chest: 108,
      arm: 61,
      neck: 42,
      cuff: 24,
      expansion: 1,
    },
    fabricRollId: 'fab-6',
    fabricName: 'قماش تويوبو بلاتينيوم ياباني - ربع واقف ناعم',
    fabricCode: 'FL-108#',
    metersRequired: 3.5,
    totalPrice: 450,
    paidAmount: 250,
    remainingAmount: 200,
    notes: 'توسيع محيط المعصم 1 سم إضافي بناءً على طلب الزبون.',
    paymentMethod: 'شبكة مدى',
  },
  {
    id: 'ord-9842',
    orderNumber: 'ORD-9842#',
    customerName: 'سعود بن فهد الدوسري',
    customerPhone: '050 998 7712',
    isVip: true,
    status: 'ready',
    statusLabel: 'جاهز للاستلام',
    priority: 'normal',
    deliveryDate: '2024-10-24',
    deliveryDateLabel: 'اليوم، 6:00 م',
    garmentType: 'traditional_thobe',
    garmentTitle: 'ثوب قلاب كويتي فاخر',
    garmentSubtitle: 'قماش شكسبير أبيض ياباني أصلي - مقاس خاص',
    piecesCount: 1,
    progressPercent: 100,
    currentStageName: 'مرحلة الفحص والكي النهائي',
    tailorName: 'كليم الله الخياط',
    tailorVerified: true,
    measurements: {
      length: 154,
      shoulder: 47,
      chest: 110,
      arm: 62,
      neck: 43,
      cuff: 25,
      expansion: 0,
    },
    fabricRollId: 'fab-1',
    fabricName: 'قماش شكسبير ياباني أبيض أصلي',
    fabricCode: 'TY-88#',
    metersRequired: 3.5,
    totalPrice: 400,
    paidAmount: 250,
    remainingAmount: 150,
    notes: 'تسليم مع كيس قماش فاخر وعلاقة خشبية مطرزة.',
    paymentMethod: 'شبكة مدى',
  },
  {
    id: 'ord-9845',
    orderNumber: 'ORD-9845#',
    customerName: 'م. عمر خالد التميمي',
    customerPhone: '056 334 1289',
    isVip: false,
    status: 'new',
    statusLabel: 'جديد • طلب مستعجل',
    priority: 'urgent',
    deliveryDate: '2024-10-27',
    deliveryDateLabel: 'بعد 3 أيام',
    garmentType: 'luxury_blazer',
    garmentTitle: 'بليزر رسمي كحلي',
    garmentSubtitle: 'صوف إيطالي كحلي داكن 140S - بطانة حريرية',
    piecesCount: 1,
    progressPercent: 25,
    currentStageName: 'قص القماش المبدئي وتثبيت الحشو',
    tailorName: 'المعلم سراج',
    tailorVerified: true,
    measurements: {
      length: 78,
      shoulder: 48,
      chest: 104,
      arm: 64,
      neck: 41,
      cuff: 28,
      expansion: 0,
    },
    fabricRollId: 'fab-3',
    fabricName: 'صوف إنجليزي هدرسفيلد كحلي مقلم',
    fabricCode: 'ENG-12#',
    metersRequired: 2.8,
    totalPrice: 1200,
    paidAmount: 800,
    remainingAmount: 400,
    notes: 'طلب مستعجل لحضور مناسبة دبلوماسية.',
    paymentMethod: 'تحويل بنكي',
  },
  {
    id: 'ord-4921',
    orderNumber: 'ORD-4921#',
    customerName: 'سعود بن فيصل المقرن',
    customerPhone: '055 432 9876',
    isVip: false,
    status: 'tailoring',
    statusLabel: 'تسليم غداً',
    priority: 'urgent',
    deliveryDate: '2024-10-25',
    deliveryDateLabel: 'تسليم غداً',
    garmentType: 'traditional_thobe',
    garmentTitle: 'ثوب شتوي صوف إنجليزي',
    garmentSubtitle: 'ثوب شتوي صوف إنجليزي • رقبة قلاب',
    piecesCount: 1,
    progressPercent: 75,
    currentStageName: 'مرحلة البروفة وتثبيت البطانة',
    tailorName: 'المعلم سراج',
    tailorVerified: true,
    measurements: {
      length: 150,
      shoulder: 45,
      chest: 106,
      arm: 60,
      neck: 42,
      cuff: 24,
      expansion: 0,
    },
    fabricRollId: 'fab-3',
    fabricName: 'صوف إنجليزي هدرسفيلد',
    fabricCode: 'ENG-12#',
    metersRequired: 3.5,
    totalPrice: 1250,
    paidAmount: 1250,
    remainingAmount: 0,
    notes: 'الخياطة بالخيط المزدوج المقوى.',
    paymentMethod: 'مدى',
  },
  {
    id: 'ord-4918',
    orderNumber: 'ORD-4918#',
    customerName: 'م. إبراهيم الخالدي',
    customerPhone: '054 223 9988',
    isVip: true,
    status: 'tailoring',
    statusLabel: 'بقي 4 أيام',
    priority: 'normal',
    deliveryDate: '2024-10-28',
    deliveryDateLabel: 'بقي 4 أيام',
    garmentType: 'traditional_thobe',
    garmentTitle: 'بشت حساوي مقصب ذهبي يدوي',
    garmentSubtitle: 'بشت حساوي مقصب ذهبي يدوي (قصب ملكي)',
    piecesCount: 1,
    progressPercent: 50,
    currentStageName: 'تطريز القصب الذهبي يدوي',
    tailorName: 'الأستاذ هاني',
    tailorVerified: true,
    measurements: {
      length: 156,
      shoulder: 49,
      chest: 114,
      arm: 63,
      neck: 44,
      cuff: 26,
      expansion: 2,
    },
    fabricRollId: 'fab-5',
    fabricName: 'حرير كوري كحلي داكن ملكي',
    fabricCode: 'KSL-441#',
    metersRequired: 4.0,
    totalPrice: 4800,
    paidAmount: 3000,
    remainingAmount: 1800,
    notes: 'قصب ألماني عيار 24 مطلي بماء الذهب.',
    paymentMethod: 'تحويل بنكي',
  },
  {
    id: 'ord-9830',
    orderNumber: 'ORD-9830#',
    customerName: 'عبد العزيز المنصور',
    customerPhone: '050 112 3344',
    isVip: false,
    status: 'delivered',
    statusLabel: 'تم التسليم • مسلّم بالمعرض',
    priority: 'normal',
    deliveryDate: '2024-10-23',
    deliveryDateLabel: 'أمس، 9:30 م',
    garmentType: 'traditional_thobe',
    garmentTitle: 'ثوب سحاب قطري',
    garmentSubtitle: 'قماش ريتشي سلك أصلي كرموز',
    piecesCount: 2,
    progressPercent: 100,
    currentStageName: 'تم التسليم وإغلاق الفاتورة',
    tailorName: 'كليم الله الخياط',
    tailorVerified: true,
    measurements: {
      length: 151,
      shoulder: 46,
      chest: 107,
      arm: 61,
      neck: 41.5,
      cuff: 24,
      expansion: 0,
    },
    fabricRollId: 'fab-2',
    fabricName: 'ريتشي سلك أصلي كرموز',
    fabricCode: 'RC-402#',
    metersRequired: 7.0,
    totalPrice: 900,
    paidAmount: 900,
    remainingAmount: 0,
    notes: 'تم الاستلام وإبداء الرضا التام.',
    paymentMethod: 'نقد',
    deliveredTime: 'أمس، 9:30 م',
  },
];

export const INITIAL_INVOICES: InvoiceItem[] = [
  {
    id: 'inv-2049',
    invoiceNumber: 'INV-2049#',
    customerName: 'فيصل العتيبي',
    customerPhone: '055 776 5432',
    dateLabel: 'اليوم',
    timeLabel: '11:30 ص',
    description: 'ثوب ياباني فاخر (عدد 2)',
    amount: 750,
    vatAmount: 97.8,
    status: 'paid',
    paymentMethod: 'مدى',
    paidAmount: 750,
    remainingAmount: 0,
  },
  {
    id: 'inv-2048',
    invoiceNumber: 'INV-2048#',
    customerName: 'طارق السعد',
    customerPhone: '053 889 0011',
    dateLabel: 'أمس',
    timeLabel: '05:40 م',
    description: 'بشت صيفي ملكي تطريز خاص',
    amount: 1200,
    vatAmount: 156.5,
    status: 'partial',
    paymentMethod: 'تحويل بنكي',
    paidAmount: 700,
    remainingAmount: 500,
  },
  {
    id: 'inv-2047',
    invoiceNumber: 'INV-2047#',
    customerName: 'بدر الشمري',
    customerPhone: '056 123 7890',
    dateLabel: 'أمس',
    timeLabel: '02:15 م',
    description: 'ثوب شتوي إنجليزي',
    amount: 450,
    vatAmount: 58.7,
    status: 'paid',
    paymentMethod: 'نقد',
    paidAmount: 450,
    remainingAmount: 0,
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'st-1',
    name: 'عبد الرحمن السبيعي',
    role: 'مدير النظام',
    department: 'الإدارة العامة • صلاحيات كاملة',
    active: true,
    initials: 'ع',
  },
  {
    id: 'st-2',
    name: 'كليم الله الخياط',
    role: 'رئيس قسم الخياطة',
    department: 'قسم التفصيل والقص • مسند له 9 طلبات',
    active: true,
    assignedOrdersCount: 9,
    initials: 'ك',
  },
  {
    id: 'st-3',
    name: 'رفيق أحمد',
    role: 'محاسب وكاشير',
    department: 'نقطة البيع #1 • الصندوق الصباحي',
    active: true,
    initials: 'ر',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'log-1',
    category: 'orders',
    title: 'تعديل مقاسات الطلب',
    timeAgo: 'قبل 12 دقيقة',
    description: 'قام المدير عبد الرحمن بتحديث عرض الصدر وطول الكم للطلب ORD-9842#',
    actor: 'عبد الرحمن السبيعي',
  },
  {
    id: 'log-2',
    category: 'financials',
    title: 'تسجيل دفعة نقدية',
    timeAgo: 'قبل 45 دقيقة',
    description: 'قام المحاسب رفيق بتسجيل سداد 250 ر.س للفاتورة الضريبية INV-2049#',
    actor: 'رفيق أحمد',
  },
  {
    id: 'log-3',
    category: 'inventory',
    title: 'صرف قماش من المستودع',
    timeAgo: 'قبل ساعتين',
    description: 'تم صرف 3.5 أمتار من طاقة قماش تويوبو الياباني TY-88# بواسطة الخياط كليم',
    actor: 'كليم الله الخياط',
  },
  {
    id: 'log-4',
    category: 'system',
    title: 'نسخة احتياطية سحابية آلية',
    timeAgo: 'أمس 10:30 م',
    description: 'أتم النظام مزامنة قواعد البيانات بنجاح بحجم 140.2 ميجابايت في الخادم السحابي',
    actor: 'نظام النسخ الآلي',
  },
];
